# This file will Create a network.
# Set up a MySQL database container.
# Set up a web application container.

version: '3.9'

services:
  database:
    image: mysql:latest
    container_name: database1
    environment:
      MYSQL_DATABASE: stackmastersdb
      MYSQL_ROOT_PASSWORD: stackmasters  # Define root password for MySQL
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  webapp:
    build:
      context: .  # Path to Dockerfile
      dockerfile: Dockerfile  # Ensure this matches the name of your Dockerfile
    container_name: stackmasters-webapp
    environment:
      DB_NAME: stackmastersdb
      DB_HOST: database1  # The service name of the MySQL container
      DB_USER: root
      DB_PASSWORD: stackmasters
      JWT_SECRET: 39cce276253d1fd1ec2ecf357bd668f12239c01f3d04e8a0e43ae720004828abf90e894f4a537d0e1f4b6bd09d5fc284c3e1217239b715146528af23289e8633
    ports:
      - "5000:5000"
      - "8000:8000"
    depends_on:
      - database
    networks:
      - my_network
    env_file:
      - ./backend/.env

volumes:
  db_data:

networks:
  my_network:
    driver: bridge


# Running it is: docker-compose up -d
# To stop and remove containers: docker-compose down

# Only to stop without removing containers: docker-compose stop
# Remove Containers, Networks, and Volumes: docker-compose down -v
