#this yml file is for automating creating the database, and wep app and running them on azure
#but you will need github secrets
name: CI/CD Pipeline for Azure

on:
  push:
    branches:
      - Testing  # Change to your default branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: stackmasterscont.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build Docker Image
      run: |
        docker build -t stackmasterscont.azurecr.io/your-image-name:latest .

    - name: Push Docker Image
      run: |
        docker push stackmasterscont.azurecr.io/your-image-name:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: HMS-StackMasters
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
