name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Frontend
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Frontend

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: List directory contents
        run: |
          ls -R

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust as needed

      - name: Install Dependencies
        run: |
          cd StackMasters-WebApp/Frontend
          npm install

      - name: Build
        run: |
          cd StackMasters-WebApp/Frontend
          npm run build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_MEADOW_0EB222D03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          app_location: "StackMasters-WebApp/Frontend"  # Path to your app
          api_location: ""                                # Optional, leave empty if not used
          output_location: "StackMasters-WebApp/Frontend/build"  # Where the built files are located
