name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        run: az acr login --name stackmastersCont

      - name: Build and Tag Docker Image
        run: |
          docker build -t stackmasters-webapp .
          docker tag stackmasters-webapp stackmasterscont.azurecr.io/stackmasters-webapp:v1

      - name: Push Docker Image to ACR
        run: docker push stackmasterscont.azurecr.io/stackmasters-webapp:v1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: '<your-app-service-name>'
          images: 'stackmasterscont.azurecr.io/stackmasters-webapp:v1'
